// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/volatrade/conduit/internal/cache (interfaces: Cache)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/volatrade/conduit/internal/models"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// CandleStickRowsLength mocks base method.
func (m *MockCache) CandleStickRowsLength() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CandleStickRowsLength")
	ret0, _ := ret[0].(int)
	return ret0
}

// CandleStickRowsLength indicates an expected call of CandleStickRowsLength.
func (mr *MockCacheMockRecorder) CandleStickRowsLength() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CandleStickRowsLength", reflect.TypeOf((*MockCache)(nil).CandleStickRowsLength))
}

// GetAllCandleStickRows mocks base method.
func (m *MockCache) GetAllCandleStickRows() []*models.CandleStickRow {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCandleStickRows")
	ret0, _ := ret[0].([]*models.CandleStickRow)
	return ret0
}

// GetAllCandleStickRows indicates an expected call of GetAllCandleStickRows.
func (mr *MockCacheMockRecorder) GetAllCandleStickRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCandleStickRows", reflect.TypeOf((*MockCache)(nil).GetAllCandleStickRows))
}

// GetAllOrderBookRows mocks base method.
func (m *MockCache) GetAllOrderBookRows() []*models.OrderBookRow {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrderBookRows")
	ret0, _ := ret[0].([]*models.OrderBookRow)
	return ret0
}

// GetAllOrderBookRows indicates an expected call of GetAllOrderBookRows.
func (mr *MockCacheMockRecorder) GetAllOrderBookRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrderBookRows", reflect.TypeOf((*MockCache)(nil).GetAllOrderBookRows))
}

// GetEntries mocks base method.
func (m *MockCache) GetEntries() []*models.CacheEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntries")
	ret0, _ := ret[0].([]*models.CacheEntry)
	return ret0
}

// GetEntries indicates an expected call of GetEntries.
func (mr *MockCacheMockRecorder) GetEntries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntries", reflect.TypeOf((*MockCache)(nil).GetEntries))
}

// InsertCandleStickRow mocks base method.
func (m *MockCache) InsertCandleStickRow(arg0 *models.CandleStickRow) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertCandleStickRow", arg0)
}

// InsertCandleStickRow indicates an expected call of InsertCandleStickRow.
func (mr *MockCacheMockRecorder) InsertCandleStickRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCandleStickRow", reflect.TypeOf((*MockCache)(nil).InsertCandleStickRow), arg0)
}

// InsertOrderBookEntry mocks base method.
func (m *MockCache) InsertOrderBookEntry(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertOrderBookEntry", arg0)
}

// InsertOrderBookEntry indicates an expected call of InsertOrderBookEntry.
func (mr *MockCacheMockRecorder) InsertOrderBookEntry(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrderBookEntry", reflect.TypeOf((*MockCache)(nil).InsertOrderBookEntry), arg0)
}

// InsertOrderBookRow mocks base method.
func (m *MockCache) InsertOrderBookRow(arg0 *models.OrderBookRow) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InsertOrderBookRow", arg0)
}

// InsertOrderBookRow indicates an expected call of InsertOrderBookRow.
func (mr *MockCacheMockRecorder) InsertOrderBookRow(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOrderBookRow", reflect.TypeOf((*MockCache)(nil).InsertOrderBookRow), arg0)
}

// OrderBookRowsLength mocks base method.
func (m *MockCache) OrderBookRowsLength() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderBookRowsLength")
	ret0, _ := ret[0].(int)
	return ret0
}

// OrderBookRowsLength indicates an expected call of OrderBookRowsLength.
func (mr *MockCacheMockRecorder) OrderBookRowsLength() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBookRowsLength", reflect.TypeOf((*MockCache)(nil).OrderBookRowsLength))
}

// PurgeOrderBookRows mocks base method.
func (m *MockCache) PurgeOrderBookRows() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PurgeOrderBookRows")
}

// PurgeOrderBookRows indicates an expected call of PurgeOrderBookRows.
func (mr *MockCacheMockRecorder) PurgeOrderBookRows() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeOrderBookRows", reflect.TypeOf((*MockCache)(nil).PurgeOrderBookRows))
}
