// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/volatrade/conduit/internal/service (interfaces: Service)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	socket "github.com/volatrade/conduit/internal/socket"
	reflect "reflect"
	sync "sync"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BuildOrderBookChannels mocks base method
func (m *MockService) BuildOrderBookChannels(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildOrderBookChannels", arg0)
}

// BuildOrderBookChannels indicates an expected call of BuildOrderBookChannels
func (mr *MockServiceMockRecorder) BuildOrderBookChannels(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildOrderBookChannels", reflect.TypeOf((*MockService)(nil).BuildOrderBookChannels), arg0)
}

// BuildTransactionChannels mocks base method
func (m *MockService) BuildTransactionChannels(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BuildTransactionChannels", arg0)
}

// BuildTransactionChannels indicates an expected call of BuildTransactionChannels
func (mr *MockServiceMockRecorder) BuildTransactionChannels(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildTransactionChannels", reflect.TypeOf((*MockService)(nil).BuildTransactionChannels), arg0)
}

// InsertPairsFromBinanceToCache mocks base method
func (m *MockService) InsertPairsFromBinanceToCache() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPairsFromBinanceToCache")
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPairsFromBinanceToCache indicates an expected call of InsertPairsFromBinanceToCache
func (mr *MockServiceMockRecorder) InsertPairsFromBinanceToCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPairsFromBinanceToCache", reflect.TypeOf((*MockService)(nil).InsertPairsFromBinanceToCache))
}

// ListenAndHandleDataChannels mocks base method
func (m *MockService) ListenAndHandleDataChannels(arg0 int, arg1 *sync.WaitGroup, arg2 chan bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenAndHandleDataChannels", arg0, arg1, arg2)
}

// ListenAndHandleDataChannels indicates an expected call of ListenAndHandleDataChannels
func (mr *MockServiceMockRecorder) ListenAndHandleDataChannels(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndHandleDataChannels", reflect.TypeOf((*MockService)(nil).ListenAndHandleDataChannels), arg0, arg1, arg2)
}

// ListenForDatabasePriveleges mocks base method
func (m *MockService) ListenForDatabasePriveleges(arg0 *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenForDatabasePriveleges", arg0)
}

// ListenForDatabasePriveleges indicates an expected call of ListenForDatabasePriveleges
func (mr *MockServiceMockRecorder) ListenForDatabasePriveleges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForDatabasePriveleges", reflect.TypeOf((*MockService)(nil).ListenForDatabasePriveleges), arg0)
}

// ListenForExit mocks base method
func (m *MockService) ListenForExit(arg0 *sync.WaitGroup, arg1 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenForExit", arg0, arg1)
}

// ListenForExit indicates an expected call of ListenForExit
func (mr *MockServiceMockRecorder) ListenForExit(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForExit", reflect.TypeOf((*MockService)(nil).ListenForExit), arg0, arg1)
}

// SpawnSocketRoutines mocks base method
func (m *MockService) SpawnSocketRoutines(arg0 int) []*socket.BinanceSocket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnSocketRoutines", arg0)
	ret0, _ := ret[0].([]*socket.BinanceSocket)
	return ret0
}

// SpawnSocketRoutines indicates an expected call of SpawnSocketRoutines
func (mr *MockServiceMockRecorder) SpawnSocketRoutines(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnSocketRoutines", reflect.TypeOf((*MockService)(nil).SpawnSocketRoutines), arg0)
}
