cat > config.env << EOF
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}

HOST=${PG_HOST}
PORT=5432
DATABASE=${PG_DATABASE}
POSTGRES_USER=${PG_USER}
PASSWORD=${PG_PASSWORD}

STORAGE_CONNECTION_COUNT=${STORAGE_CONNECTION_COUNT}

STATS_HOST=${STATS_HOST}
STATS_PORT=${STATS_PORT}

#environment
ENV=${ENV}
