cat > config.env << EOF
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}

PG_HOST=${PG_HOST}
PG_PORT=${PG_PORT}
PG_DATABASE=${PG_DATABASE}
PG_USER=${PG_USER}
PG_PASSWORD=${PG_PASSWORD}

STORAGE_CONNECTION_COUNT=${STORAGE_CONNECTION_COUNT}

GATEKEEPER_URL=${GATEKEEPER_URL}
REQUEST_TIMEOUT=${REQUEST_TIMEOUT}

CORTEX_URL=${CORTEX_URL}
CORTEX_PORT=${CORTEX_PORT}

STATS_HOST=${STATS_HOST}
STATS_PORT=${STATS_PORT}

#environment
ENV=${ENV}
DISPATCH_INTERVAL=${DISPATCH_INTERVAL}

CONVEYOR_COUNT=${CONVEYOR_COUNT}
FLUSH_INTERVAL=${FLUSH_INTERVAL}
GRAPHITE_URL=${GRAPHITE_URL}
GRAPHITE_API_KEY=${GRAPHITE_API_KEY}
GRAPHITE_REQUEST_TIMEOUT=${GRAPHITE_REQUEST_TIMEOUT}
SERVICE_NAME=${SERVICE_NAME}