cat > config.env << EOF
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=${AWS_REGION}

POSTGRES_HOST=voladata.cluster-cllfpcynhvtf.us-west-2.rds.amazonaws.com
POSTGRES_PORT=5432
POSTGRES_DATABASE=voladata
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${PG_PASSWORD}
EOF 