version: "3.2"
services:
    candles:
        build:
            context: .
            args: 
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        image: candles:latest
        container_name: candles
        restart: always