version: "3.2"
services:
    db:
        image: postgres
        restart: always
        volumes:
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: "voladata"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"

    candles:
        build:
            context: .
            args: 
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        image: candles:latest
        container_name: candles
        restart: always
        