version: "3.5"

services:
  conduit_redis:
    container_name: conduit_redis
    image: redis:5.0.3
    ports:
      - "6379:6379"
    networks:
      - compose

  conduit-postgres:
    container_name: conduit_postgres
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_USER: "cortexer"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
        - ./ddl/ddl.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - compose

networks:
  compose:
    name: conduit-compose
