version: '3'
services:
  tickers:
    image: 752939442315.dkr.ecr.us-west-2.amazonaws.com/tickers:1.0.0
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"