version: "3.2"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: "voladata"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"

    candles:
        build:
            context: .
            args: 
                GITHUB_TOKEN: ${GITHUB_TOKEN}
        command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
        image: candles:latest
        container_name: candles
        restart: always
        depends_on:
            - db
        links:
            - db