// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/volatrade/conduit/internal/cache"
	"github.com/volatrade/conduit/internal/client"
	"github.com/volatrade/conduit/internal/config"
	"github.com/volatrade/conduit/internal/connections"
	"github.com/volatrade/conduit/internal/driver"
	"github.com/volatrade/conduit/internal/service"
	"github.com/volatrade/k-stats"
	"github.com/volatrade/utilities/slack"
)

// Injectors from wire.go:

func InitializeAndRun(cfg config.FilePath) (driver.Driver, error) {
	configConfig := config.NewConfig(cfg)
	postgresConfig := config.NewDBConfig(configConfig)
	statsConfig := config.NewStatsConfig(configConfig)
	statsStats, err := stats.New(statsConfig)
	if err != nil {
		return nil, err
	}
	connectionArray := connections.New(postgresConfig, statsStats)
	conduitCache := cache.New()
	apiClient := client.New(statsStats)
	slackConfig := config.NewSlackConfig(configConfig)
	slackLogger := slack.New(slackConfig)
	conduitService := service.New(connectionArray, conduitCache, apiClient, statsStats, slackLogger)
	conduitDriver := driver.New(conduitService, statsStats)
	return conduitDriver, nil
}

// wire.go:

var cacheModule = wire.NewSet(cache.Module, wire.Bind(new(cache.Cache), new(*cache.ConduitCache)))

var serviceModule = wire.NewSet(service.Module, wire.Bind(new(service.Service), new(*service.ConduitService)))

var connectionModule = wire.NewSet(connections.Module, wire.Bind(new(connections.Connections), new(*connections.ConnectionArray)))

var apiClientModule = wire.NewSet(client.Module, wire.Bind(new(client.Client), new(*client.ApiClient)))

var driverModule = wire.NewSet(driver.Module, wire.Bind(new(driver.Driver), new(*driver.ConduitDriver)))

var slackModule = wire.NewSet(slack.Module, wire.Bind(new(slack.Slack), new(*slack.SlackLogger)))
