version: "3.8"
services:
  conduit_postgres:
    container_name: conduit_postgres
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_USER: conduiter
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - compose 
  postgres_seed:
    container_name: postgres_seed
    build:
      context: ../
      dockerfile: .docker/postgres_seed/Dockerfile
    networks:
        - compose
    depends_on:
        - conduit_postgres

networks: 
  compose: 
    name: conduit-compose