version: "3.8"
services:
  conduit_redis:
    container_name: conduit_redis
    image: redis:5.0.3
    ports:
        - "6379:6379"
    networks:
      - compose

  conduit_postgres:
    container_name: conduit_postgres
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_USER: conduiter
      POSTGRES_PASSWORD: password
    networks:
      - compose 
  postgres_seed:
    container_name: postgres_seed
    build:
      context: ../
      dockerfile: .docker/postgres_seed/Dockerfile
    networks:
        - compose
    depends_on:
        - conduit_postgres

networks: 
  compose: 
    name: conduit-compose